version: "3.3"
services:
  web:
    image: gbs-m183_web
    build:
      context: .
      dockerfile: .docker/php.Dockerfile
      network: host
    volumes:
      - .:/var/www/html
    ports:
      - "8081:80"
    networks:
      - public
      - local
    hostname: web
    restart: "no"

# volumes:
#   <service>-data: null

networks:
  public:
    internal: false
  local:
    internal: true
