version: "3.3"
services:
  web:
    image: gbs-m183_web
    build:
      context: .
      dockerfile: .docker/php.Dockerfile
      network: host
    volumes:
      - .:/var/www/html
    ports:
      - "8081:80"
    networks:
      - public
      - local
    hostname: web
    restart: "no"
  db:
    image: mariadb:10.8
    command: ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - sql-data:/var/lib/mysql
    networks:
      - local
    hostname: db
    restart: "no"
  phpmyadmin:
    image: phpmyadmin:5.1
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
      UPLOAD_LIMIT: 50M
    ports:
      - "8082:80"
    networks:
      - public
      - local
    hostname: phpmyadmin
    restart: "no"

volumes:
  sql-data: null

networks:
  public:
    internal: false
  local:
    internal: true
